owner_org: "hdx"
maintainer: "mcarans"
maintainer_email: "rans@un.org"
license_id: "cc-by-igo"
subnational: 1  # has to be 0 or 1
methodology: "Other"
dataset_source: "IDMC"
package_creator: "mcarans"
private: False  # has to be True or False
url: ~
state: "active"  # always "active".
