# Collector specific configuration
base_url: "https://api.idmcdb.org/api/"
endpoints:
  - "conflict_data"
  - "disaster_data"
  - "displacement_data"
tags:
  - "population"
  - "displacement"
  - "idmc"


